### PR TITLE
Make AppDir and AppImage the default for linux

### LINKED ISSUE #49: Not able to run the linux version on fedora, undefined symbol related to some python lib Qt_5
I downloaded the tar and ran it on fedora, but i get this error:
`./minikube-gui: symbol lookup error: ./minikube-gui: undefined symbol: _ZdlPvm, version Qt_5`

### PR DESCRIPTION
**Pull request by afbjorklund**
Add [AppDir](https://en.wikipedia.org/wiki/Application_directory) files to the tarball so that is possible to run.

`AppRun  .DirIcon  minikube-gui  minikube-gui.desktop  minikube.png  usr/`

Create an [AppImage](https://appimage.org/) to get an all-in-one similar to the dmg.

`minikube-gui-linux.AppImage` 

Closes #49

----

Uses:

* https://github.com/probonopd/linuxdeployqt

See also:

* https://docs.appimage.org/packaging-guide/manual.html

### CODE REVIEW

**Comment by afbjorklund** [comment]
@medyagh can we test this, to see if the `linuxdeployqt` program is installed by default or needs adding ?

**Comment by afbjorklund** [comment]
No such luck: `/bin/sh: 2: linuxdeployqt: not found`

So we need to download and install it, I suppose...

----

```bash
curl -LO https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
sudo install linuxdeployqt-continuous-x86_64.AppImage /usr/local/bin/linuxdeployqt
```

**Comment by afbjorklund** [comment]
@medyagh try again ? added a commit to install the missing `linuxdeployqt` program

**Comment by afbjorklund** [comment]
* https://github.com/jurplel/install-qt-action/issues/204

**Comment by afbjorklund** [comment]
ping @spowelljr

**Comment by medyagh** [comment]
@afbjorklund is the test/build happy now?

**Comment by afbjorklund** [comment]
Looks happy:

minikube-gui-linux

Was just to `chmod +x` and run, all dependencies bundled within the single file:

`minikube-gui-linux.AppImage`

**Comment by afbjorklund** [comment]
There is some extra file though, "Minikube--x86_64.AppImage" - it looks like some kind of leftover

I think it was supposed to have the version in the filename but it looks like `VERSION` is empty ?

**Comment by medyagh** [comment]
> inikube--x86_64.AppImage" - it looks like some kind of leftover
> 
> I think it was supposed to have the version in the filename but it looks like `VERSION` is empty ?

not sure, can we merge this PR now ?

**Comment by afbjorklund** [comment]
It seems like VERSION is not set for the PR, but only for the release builds - should be OK to merge

**Comment by afbjorklund** [comment]
Added support for adwaita-qt, so that one can use `adwaita` or `adwaita-dark` styles...

Previous error message:

```
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
```

light
minikube-gui-linux-light
dark
minikube-gui-linux-dark

**Comment by afbjorklund** [comment]
The installation ended up in some weird place, so it didn't make into the tarball:


-- Installing: /home/runner/work/minikube-gui/minikube-gui/bin/adwaita-qt-1.4.2/dest/usr/lib/x86_64-linux-gnu/libadwaitaqtpriv.so.1

-- Installing: /home/runner/work/minikube-gui/minikube-gui/bin/adwaita-qt-1.4.2/dest/usr/lib/x86_64-linux-gnu/libadwaitaqt.so.1

-- Installing: /home/runner/work/minikube-gui/minikube-gui/bin/adwaita-qt-1.4.2/dest/home/runner/work/minikube-gui/Qt/5.15.2/gcc_64/plugins/styles/adwaita.so

+ cp adwaita-qt-1.4.2/dest/usr/lib/x86_64-linux-gnu/libadwaitaqt.so.1 usr/lib
+ cp adwaita-qt-1.4.2/dest/usr/lib/x86_64-linux-gnu/libadwaitaqtpriv.so.1 usr/lib

+ cp adwaita-qt-1.4.2/dest/usr/lib/*/qt5/plugins/styles/adwaita.so usr/plugins/styles
cp: cannot stat 'adwaita-qt-1.4.2/dest/usr/lib/*/qt5/plugins/styles/adwaita.so': No such file or directory


Need to configure that, so that it installs into some sane place (and not in homedir)

**Comment by afbjorklund** [comment]
Linux looks good now.

**Pull request merged**
