### PR TITLE
feat: add Tiny button next to each feature for Documentation link

### PR DESCRIPTION
**Pull request by zitudu**
Implemented issue #25. Will open URL like https://minikube.sigs.k8s.io/docs/commands/XXX using the default browser.

Screenshot from 2023-07-19 16-24-33

### CODE REVIEW

**Comment by zitudu** [comment]
ping @medyagh

**Review by medyagh — CHANGES_REQUESTED** [review]
hi @zitudu thank you for this contribution  can we make the icon smaller and tiny and also change the grapgic to look like documentaion?

**Comment by zitudu** [comment]
> hi @zitudu thank you for this contribution can we make the icon smaller and tiny and also change the grapgic to look like documentation?

The link button is now smaller and align bottom.

Screenshot from 2023-07-28 16-44-23

The external link symbol is widely used to open resource links, such as the minikube-gui documentation page also uses this symbol. Any suggestions, please?

image

**Comment by zitudu** [comment]
ping @medyagh @spowelljr

**Comment by zitudu** [comment]
Hi @medyagh I'm still waiting for your reply. Could you please tell me more information about this issue?

**Comment by medyagh** [comment]
sorry @zitudu for the long wait, can we change the icon to something else? maybe "i" information icon ?

**Comment by zitudu** [comment]
> maybe "i" information icon ? and maybe it should be gray and only be Darker if you Hover over it it. and then it should tooltip "documentation"

Changes made according to the above description. Is this what we expected?

Screenshot from 2023-08-31 17-07-26
Screenshot from 2023-08-31 17-16-55

**Comment by medyagh** [comment]
@zitudu thanks for the new update, looks better but the build failed, plz take a look

**Comment by medyagh** [comment]
```
In file included from src/window.h:41:
In file included from src/basicview.h:23:
src/linkbutton.h:36:41: error: non-virtual member function marked 'override' hides virtual member function
    void enterEvent(QEnterEvent *event) override;
                                        ^
/Users/runner/work/minikube-gui/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qwidget.h:631:18: note: hidden overloaded virtual function 'QWidget::enterEvent' declared here: type mismatch at 1st parameter ('QEvent *' vs 'QEnterEvent *')
    virtual void enterEvent(QEvent *event);
                 ^
1 error generated
```

**Comment by zitudu** [comment]
@medyagh This is due to the different signatures of this method in qt5 and qt6. I added support for qt5 and built it successfully locally.

**Pull request closed without merging**
